### ISSUE TITLE
Analysis is complete but pipeline reports failure

### ISSUE THREAD

**Issue by strimber** [cathive/concourse-sonarqube-resource#10]
Hello,
I've successfully built and run the put:  sonarqube-analysis on my java project however the pipeline continues to report 'failed'.  I see the analysis results published on our sonarqube.

I am not running the qualitygate task which may break the build.  My job pipeline ends after the sonarqube-analysis put:  

The GUI shows an UP arrow with a green checkmark after the put.  I assume the UP arrow represents a put?  It then shows a down arrow on the resource and ends with a blank line and a red "X".  
Am I missing a step?
Thanks!
Scott

**Comment by headcr4sh** [comment]
Looks like an error during check/in step.
(You are right: after the put step [up arrow] has been performed, Concourse always performs the get step [down arrow])

I'll need more input to check what's going on here.

Can you use fly to intercept/hijack the put step? Maybe the contents of the generated sonar-report.txt can help us find the issue.

Some more questsions:
* Which version of Concourse CI are you using?
* Which version of SonarQube are you using?
* Which version/tag of the concourse-sonarqube-resource are you using?
* Is this a Maven project that is being analyzed?

**Comment by strimber** [comment]
Hello,
Thanks for the quick response!  
Concourse version: 3.8.0
SonarQube version: 6.7.1
Version tag:  latest
This is a gradle java project that we are building.

Let me capture the put step via hijack to grab the sonar-report.txt file.  I'll report back.
regards
Scott

**Comment by strimber** [comment]
Contents of report-task.txt in put:
--------------
projectKey=GRCI-grcore-GRCORE:master
serverUrl=http://<masked IP>:9000
serverVersion=6.7.1.35068
dashboardUrl=http://<masked IP>:9000/dashboard/index/GRCI-grcore-GRCORE:master
ceTaskId=AWEkkmf94fPDbzJJYupb
ceTaskUrl=http://<masked IP>:9000/api/ce/task?id=AWEkkmf94fPDbzJJYupb

**Comment by strimber** [comment]
contents of get:
ce_task.json is empty

**Comment by headcr4sh** [comment]
I am using the exact same versions of SonarQube and Concourse CI.


The serverUrl looks really Strange.

Could it be that you did not configure your SonarQube server's base URL?
(Paramter `sonar.core.serverBaseURL` in `conf/sonar.properties`)
Please try to change that URL.

The resource fetches ce_task.json by using the ```ceTaskUrl``` parameter... and this parameter obviously also contains an empty string as hostname!

I'll try to provide some kind of debug flag to make sure that the output of the resource can be used to trace errors, such as the one that has occured to you, a bit easier.

**Comment by strimber** [comment]
Thank you headcr4sh. 

You can close this issue... it was a configuration problem with my host url.  missing leading "/"  caused the "check" and "in" api calls to fail. Once I corrected this format, the build turned green!  :-)

A debug flag would be great!  My team is new to Concourse so tracing through this resource has been a great learning experience. 
Thanks for your support and very helpful feedback.
Scott

**Comment by headcr4sh** [comment]
Glad to hear, that it works now as expected.
Debug flag is on my agenda....

**Comment by santus444** [comment]
Thanks @strimber @headcr4sh  , had similar issue where the Server base Url was missing trailing '/' in sonarqube settings.
