### ISSUE TITLE
Anonymous analysis

### ISSUE THREAD

**Issue by TomRK1089** [cathive/concourse-sonarqube-resource#13]
The `login` parameter is required on the resource definition. However my Sonar instance is on a private network and doesn't require a username or access token to push analysis results to.

Leaving the login field blank in my pipeline YAML doesn't seem to work.

How can I use this resource with an open Sonarqube instance?

**Comment by headcr4sh** [comment]
You are right, the login parameter *is* mandatory.
I assume that even when running SonarQube on a private network it is a good idea to create a different user for the CI/CD system. One advantage e.g. is that you can easily distinguish between analysis-runs that have been triggered by the CI/CD system and those triggered by another user.

```assets/common.sh``` would need to be patched if an open SonarQube instance is indeed a valid use-case. I will probably not find the time to provide a patch myself in the next few days-- but I'll gladly except one if it doesn't break anyhing else. ;-)
