### ISSUE TITLE
Error in out script when using custom maven settings.xml

### ISSUE THREAD

**Issue by marek-urban** [cathive/concourse-sonarqube-resource#19]
Using custom **settings.xml**  with custom artifactory on a multi module maven project makes this error:

`++ error 161 1` 
`++ JOB=/opt/resource/out`
`++ LASTLINE=161`
`++ LASTERR=1`
`++ echo 'ERROR in /opt/resource/out : line 161 with exit code 1'`
`ERROR in /opt/resource/out : line 161 with exit code 1`
`++ exit 1`

The problem is in line 161 of OUT script file where following cmd is build and executed:

> mvn -X -q -f sonarqube-analysis-input/pom.xml -Dexec.executable=echo '-Dexec.args=${project.build.directory}' --non-recursive exec:exec

In a command mentioned above should be inserted parsed values of **maven_settings** or **maven_settings_file**.

Please implement values from **maven_settings** or **maven_settings_file** into this mvn command.
Becareful, there might be more places where values of **maven_settings/maven_settings_file** should be inserted.

Fixed mvn command with argument **maven_settings** set to **"_config/settings.xml_"** should looks like:

> mvn -X -q -f sonarqube-analysis-input/pom.xml -Dexec.executable=echo '-Dexec.args=${project.build.directory}' --non-recursive exec:exec --settings config/settings.xml

Regards,
Marek Urban

**Comment by marek-urban** [comment]
I have fixed this issue in my fork of this project.
Check out: [https://github.com/marek-urban/concourse-sonarqube-resource](url)

**Comment by headcr4sh** [comment]
Hi Marek,

I have checked your fork. Seems as if you have made quite a bunch of changes to the resource.
Can you share a single Pull Request that contains only the changes necessary to fix the issue at hand?

**Comment by marek-urban** [comment]
Sure,

I have created pull request and also included the out script file with a necessary fix to solve the issue.
