### ISSUE TITLE
Improve error messaging with invalid url

### ISSUE THREAD

**Issue by wyattjsmith1** [cathive/concourse-sonarqube-resource#20]
I recently used this plugin, and it was able to upload the code to my private sonarqube instance, but it then failed on the get step without any log. Here is an image of what I saw: https://imgur.com/a/rb41Auj

As it turns out, this was because I didn't have a trailing slash at the end of my url, as the document required. Though it was documented that I should have a trailing slash, a warning message with a simple description would be much appreciated. Especially since it was somehow able to upload the data without a slash. In general, software should never fail without even a log of what happened.

Thanks, Wyatt

**Comment by ejp5133** [comment]
I struggled all day with this! Thank you Wyatt!!

**Comment by headcr4sh** [comment]
I agree, that an error message (or better: graceful handling of missing trailing slashed) would be a nice improvement. If anyone is willing to provide a PR, I'll gladly merge it.
