### ISSUE TITLE
In Fails when Anonymous

### ISSUE THREAD

**Issue by esauser** [cathive/concourse-sonarqube-resource#27]
The `In` fails due to [this](https://github.com/cathive/concourse-sonarqube-resource/blob/master/assets/in#L33) check despite the documentation indicating the anonymous authentication is supported.  The `In` only succeeds if valid credentials are provided.

**Comment by headcr4sh** [comment]
Duplicate of #25 

The latest (unreleased) version of the resource should contain a fix as of now.

**Comment by esauser** [comment]
@headcr4sh when do you expect to release said version?

**Comment by esauser** [comment]
@headcr4sh confirming success.  Thanks.
