### ISSUE TITLE
in fails with UserToken

### ISSUE THREAD

**Issue by febinrejoe** [cathive/concourse-sonarqube-resource#31]
As per sonar [documentation](https://docs.sonarqube.org/display/DEV/Web+API), using UserToken does not require a password and the curl command should look like,

`curl -u THIS_IS_MY_TOKEN: https://sonarqube.com/api/user_tokens/search`

However the `in` script adds the `:` only if `source.password` is provided. This causes the curl to prompt for a password.

I believe this can be fixed as below.

```
if [[ ! -z "${sonar_login}" ]] && [[ "${sonar_login}" != "" ]]; then
  sonar_token="${sonar_login}:"
  if [[ ! -z "${sonar_password}" ]] && [[ "${sonar_password}" != "" ]]; then
    sonar_token+="${sonar_password}"
  fi
fi
```

Let me know, I am willing to create a PR.

**Comment by headcr4sh** [comment]
Good catch. I think you are right. PR will be gladly accepted.
