### ISSUE TITLE
Unable to get maven_settings_file to work

### ISSUE THREAD

**Issue by jareon81** [cathive/concourse-sonarqube-resource#36]
Using concourse 4.2.2. Configured my resource in the following manner:
  - put: sonarqube-resource
    params:
      maven_settings_file: source-analysis-resource/settings.xml
      scanner_type: maven
      project_path: source-analysis-resource
      project_version_file: source-analysis-resource/version_file
However I notice that the maven_settings_file environment variable never gets set.
Output looks like this
++ jq -r '.source.maven_settings // ""'
+ maven_settings=
+ [[ ! -z '' ]]
+ [[ ! -z '' ]]
+ [[ ! -z '' ]]

I think if the line
elif [[ ! -z "${maven_settings_file}" ]]; then
is changed to
elif [[  -z "${maven_settings_file}" ]]; then

it would work.

**Comment by headcr4sh** [comment]
You are right, I assume.
Looks like a logic error.

I'll prepare a fix release a soon as possible.

**Comment by headcr4sh** [comment]
Release 0.8.1 (just being uploaded to Docker Hub) should fix the issue.

@jareon81 Thanks for the bug report and the proposed fix!
