### ISSUE TITLE
Increase sonarqube-qualitygate-check debug information

### ISSUE THREAD

**Issue by httran13** [cathive/concourse-sonarqube-resource#37]
Hello, when quality gate checks debug are displayed, they show very little information as in just ok/fail. To increase the level of granularity, i would like to see the rules threshold that was applied and the result from the code analysis. 

For example, a pass tests would give 

```
Work directory has been set to: "/tmp/build/e60a1a1f/code-analysis".
	
QualityGate project status: OK
	
* Metric "coverage": OK
	
* Metric "branch_coverage": OK

==> Quality Gate Goals met.
```

but when failed we have 

```
Work directory has been set to: "/tmp/build/e60a1a1f/code-analysis".
	
QualityGate project status: ERROR
	
* Metric "coverage": ERROR
	
* Metric "line_coverage": ERROR
	

	
==> Quality Gate Goals missed!
```

**Comment by SimonXming** [comment]
FYI, there is a generic quality-gate resource for Concourse. 
Ref: https://github.com/Meshcloud/gate-resource

**Comment by headcr4sh** [comment]
I assume you are talking about the output of the [Quality Gate Task container](https://github.com/cathive/concourse-sonarqube-qualitygate-task). 

Opening an issue in that repo seems like the right approach, I assume.
(I have to admit though, that it's also maintained by me. ;-))
