### ISSUE TITLE
Analysis job fails only when sonar qualitygate passes

### ISSUE THREAD

**Issue by nickyhannaway-coats** [cathive/concourse-sonarqube-resource#44]
I am currently using version 0.9.1 of the resource and when the SonarCloud QualityGate is failed the resource correctly parses the report and fails the build and the report output is visible in the pipeline step's output.

However the issue here is that when the QualityGate is in a passed state it appears that the resource can't find the report and the step fails.  The publishing to Sonar is definitely still happening as I have verified via the SonarCloud web UI.  When turning debugging logging on the output reads 'SonarQube report could not be located'.

I am using the auto scanner_type for clarification.

**Comment by headcr4sh** [comment]
Should be fixed by PR #45 which was provided by @fftorres.

Release v0.10.0 will contain the fix.
