### ISSUE TITLE
TypeScript Analysis Support

### ISSUE THREAD

**Issue by Lubytes** [cathive/concourse-sonarqube-resource#48]
I'd love for this resource to also support Typescript analysis, which would require the docker image to contain node (already done) and typescript with a global reference. This seems to be a [common issue](https://community.sonarsource.com/t/error-cannot-find-module-typescript/4396) elsewhere. Thoughts?

**Comment by headcr4sh** [comment]
I have removed TypeScript in a previous commit which seems like a bad idea as it breaks existing stuff.

I think, that a globally installed TypeScript in the resource image is a bad idea, but I definitely don't want to break stuff for existing users and I will therefore add it once again.

Thanks for the report.

**Comment by headcr4sh** [comment]
New release v0.11.0 contains TypeScript once again.
