### ISSUE TITLE
Could not find 'java' executable in JAVA_HOME or PATH.

### ISSUE THREAD

**Issue by acarsercan** [cathive/concourse-sonarqube-resource#49]
Hi,

Anything change recently?

`Preparing SonarQube scanner...
Starting sonar-scanner (type: cli)...
Could not find 'java' executable in JAVA_HOME or PATH.
ERROR in /opt/resource/out : line 265 with exit code 1
`

Regards

**Comment by headcr4sh** [comment]
Oh dear. I must have overlooked something when updating the underlying Java Runtime. I'll have a look.

**Comment by acarsercan** [comment]
Not sure what happened (or happening) but I set the resource tag from latest to 9.0.1, task passed, then went back to latest, passed again

Any ideas?

**Comment by headcr4sh** [comment]
> Not sure what happened (or happening) but I set the resource tag from latest to 9.0.1, task passed, then went back to latest, passed again

Possibly, your Docker image cache plays some tricks on you. ;-)
My recommendation is to always use tagged container images of this resource to avoid "works-sometimes" situations. ;-)

The "latest" tag is always built from the current Git "master" branch and therefore *not* considered to be stable.

**Comment by acarsercan** [comment]
Sure. Thanks for the replies. I will close for now

**Comment by headcr4sh** [comment]
Thanks for the bug report anyway. The current master branch was *indeed* broken and therefore it is much appreciated. :-)

I am about to add a container-structure-test to make sure that such things won't happen again anytime soon.

I am re-opening this issue to make sure it will be properly closed by my upcoming commit.
