### ISSUE TITLE
Version: 0.11.1- Getting Could not find 'java' executable in JAVA_HOME or PATH.

### ISSUE THREAD

**Issue by msekar2015** [cathive/concourse-sonarqube-resource#50]
Could not find 'java' executable in JAVA_HOME or PATH.
+++ error 265 1
+++ JOB=/opt/resource/out
+++ LASTLINE=265
+++ LASTERR=1
+++ echo 'ERROR in /opt/resource/out : line 265 with exit code 1'
ERROR in /opt/resource/out : line 265 with exit code 1

**Comment by dublis1** [comment]
I'm having the same issue.

**Comment by headcr4sh** [comment]
Please try again with the latest version (v0.11.2) and let me know if it works as supposed now.
