### ISSUE TITLE
Allow branch_name and branch_target to be read from files

### ISSUE THREAD

**Issue by xsorifc28** [cathive/concourse-sonarqube-resource#52]
I'm not able to decorate PR since I can't read in the head and base branch from files.
Unless there is another method I'm aware of, it would be helpful to allow for this:
```
branch_name_file: some_output/branch_name
branch_target_file: some_output/branch_target
```

Currently, concourse gives an error:
```Could not target requested branch: Target branch 'some_output/head_branch_name' does not exist```

**Comment by headcr4sh** [comment]
Seems like a legit feature request.
If you are willing to submit a PR, I'll gladly merge it. :-)
