### ISSUE TITLE
Possibility to enable bash globstar?

### ISSUE THREAD

**Issue by pnedunuri** [cathive/concourse-sonarqube-resource#60]
Hi,

`sonar.java.libraries: "**/build/libs/**/*.jar"`

Is it possible to enable bash globstar [shopt -s globstar] in the resource? The problem we have is our developers can possibly generate jars at multiple levels and with bash globstar disabled the results are inconsistent. Appreciate any help! Thank you!

**Comment by headcr4sh** [comment]
Unfortunately, this is something that I haven't tried, yet.
Any help / insights are therefore appreciated.

Does `shopt -s globstar` possibly break any existing behavior of the resource?

**Comment by pnedunuri** [comment]
I tested with the change, saw some issues and couldn't look into them. Now we need this feature on priority, will update you soon.

**Comment by headcr4sh** [comment]
Closed by #63.
