### ISSUE TITLE
maven_settings and maven_settings_file question

### ISSUE THREAD

**Issue by cyclump** [cathive/concourse-sonarqube-resource#64]
This issue refers to lines 70-90 in [assets/out](https://github.com/cathive/concourse-sonarqube-resource/blob/0a209a4a69b862c88c4e8af5c6222e40bd4a9f69/assets/out#L70).

I am puzzled by the intent of the maven_settings parameter in the source config.  The parameter is captured on line 73.  If the value is found in the source config, the value specified is stored in a temp file and the name of the tempfile is stored in maven_settings_file.   If it is not specified in the source, it is harvested from the parameters for the step and that value is stored in maven_settings_file.  

This presents the same variable with potentially two different types of values.  

- If we specify in the source, then maven_settings_file is a temp file that contains the value itself.  
- If we don't specify in the source and do specify in the parameters, maven_settings_file is the name of the file that has the settings.  
- If we specify both, the source is preferred instead of using the parameters setting which runs counter to the documentation in the readme.

My question is, when using maven_settings, is that supposed to be something like
```yaml
resources:
- name: code-analysis
  type: sonar-runner
  source:
    login: <... token here ...>
    host_url: http://my-sonar.domain.net/
    maven_settings: |
        <?xml version="1.0" encoding="UTF-8"?>
        <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <profiles>
            <profile>
            <repositories>
                <repository>
                <snapshots>
                    <enabled>false</enabled>
                </snapshots>
                <id>central</id>
                <name>libs-release</name>
                <url>https://corporate-proxy-repo:443/artifactory/libs-release</url>
                </repository>
                <repository>
                <snapshots />
                <id>snapshots</id>
                <name>libs-snapshot</name>
                <url>https://corporate-proxy-repo:443/artifactory/libs-snapshot</url>
                </repository>
            </repositories>	
            <pluginRepositories>
                <pluginRepository>
                <snapshots>
                    <enabled>false</enabled>
                </snapshots>
                <id>central</id>
                <name>libs-release</name>
                <url>https://corporate-proxy-repo:443/artifactory/libs-release</url>
                </pluginRepository>
                <pluginRepository>
                <snapshots />
                <id>snapshots</id>
                <name>libs-snapshot</name>
                <url>https://corporate-proxy-repo:443/artifactory/libs-snapshot</url>
                </pluginRepository>
            </pluginRepositories>
            <id>artifactory</id>
            </profile>
        </profiles>
        <activeProfiles>
            <activeProfile>artifactory</activeProfile>
        </activeProfiles>
        </settings>
```

Or is it supposed to just point to a file like
```yaml
resources:
- name: code-analysis
  type: sonar-runner
  source:
    login: <... token here ...>
    host_url: http://my-sonar.domain.net/
    maven_settings: sonar-source-files/maven_settings.xml
```

**Comment by headcr4sh** [comment]
It is supposed to work as mentioned in your first example, thus: `maven_settings` should contain the complete *contents* of your maven settings.xml file, whereas `maven_settings_file` points to the location of your settings file.

**Comment by headcr4sh** [comment]
You are right, that the documentation is wrong about the order in which both parameters are being evaluated. I think it would be far better to throw an error if both parameters are specified as such a configuration will probably indicate that something is not quite right...
