### ISSUE TITLE
Jobs fail with "realpath: '': No such file or directory"

### ISSUE THREAD

**Issue by defsprite** [cathive/concourse-sonarqube-resource#67]
```
Preparing SonarQube scanner...
realpath: '': No such file or directory
ERROR in /opt/resource/out : line 85 with exit code 1
```

[This commit](https://github.com/cathive/concourse-sonarqube-resource/commit/8808da547ed8a69f1331b612e1be8ff4337554d2) causes a regression for folks using CLI scans without maven settings. All jobs fail now.

**Comment by headcr4sh** [comment]
Duplicate of #66
