### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [cathive/concourse-sonarqube-resource#71]
Hi Team,
I am trying to use **cathive/concourse-sonarqube-resource** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.
I was trying to build the image on the arm64 platform using the command **docker build -t <image_name> .**  but it looks that **debian:jessie** image is not available for arm64 so replaced it with **debian:latest** and the image was built successfully.

Do you have any plans on releasing arm64 images?

I have used buildx in Github actions to build and push the image for both platforms.

**Commit Link** - https://github.com/odidev/concourse-sonarqube-resource/commit/2ca2579fe7c8465185239956a956b2b9b2ad3c98

**Github actions Link** - https://github.com/odidev/concourse-sonarqube-resource/runs/1916960248?check_suite_focus=true

**Dockerhub Link** - https://hub.docker.com/repository/registry-1.docker.io/odidev/concourse-sonarqube-resource/tags?page=1&ordering=last_updated

Please share your opinion on this. If interested, I will raise a PR.

**Comment by headcr4sh** [comment]
Hi @odidev ,

I had a quick look at your Github action and it looks very promising.
I think it would make sense to build the linux-amd64 and the linux-arm64 variants of the image the same way, therefore a Pull request with your changes would be appreciated.

One question though: I *think* that you handled Git tags already to make sure that the right docker tags are being pushed as well. Can you confirm / make sure, that a Git tag of `vA.B.C` results in the Docker tag `vA.B.C`?

**Comment by odidev** [comment]
I have created a new tag **v0.13.3** in github and the images pushed to dockerhub are with tag **v0.13.3** and **latest**.

**Github actions Link** - https://github.com/odidev/concourse-sonarqube-resource/runs/1927090956?check_suite_focus=true

**Dockerhub Link** - https://hub.docker.com/repository/registry-1.docker.io/odidev/concourse-sonarqube-resource/tags?page=1&ordering=last_updated

**Comment by odidev** [comment]
Raised [PR](https://github.com/cathive/concourse-sonarqube-resource/pull/72)
