### ISSUE TITLE
Sonarqube for python

### ISSUE THREAD

**Issue by Keets25** [cathive/concourse-sonarqube-resource#74]
I am relatively new to Sonarqube and Concourse. I came across this resource in Concourse and had a look at Dockerfile. 

- Does this support only Java application or it is applicable for Python Django Framework,since in dockerfile we use Java JRE,JDK's and maven plugins , and no python related plugins are used. 

- If it doesn't support python can I know if it can be done and if this requires maven setup since the code coverage shows 0% for my application and it doesn't generate any reports to test the code coverage.  

Thanks in Advance.

**Comment by holgerstolzenberg** [comment]
This resource starts a sonar-scanner process. So yes, everything the Sonar can analyse can be analysed. Im am not aware if Sonar can identify Django issues, but analysing Python should be possible.
