### ISSUE TITLE
ignore_all_error parameter type is not a bool

### ISSUE THREAD

**Issue by mrdimfox** [cathive/concourse-sonarqube-resource#89]
_Version: v0.14.2_

README states that `quality_gate.ignore_all_error` has type `bool`. But actually, it is compared against `ERROR` string.

https://github.com/cathive/concourse-sonarqube-resource/blob/709aa2753f4c603fb52ef03e190b6d8795b008c0/assets/common.sh#L149

Probably a copy-pasta bug from line 147

https://github.com/cathive/concourse-sonarqube-resource/blob/709aa2753f4c603fb52ef03e190b6d8795b008c0/assets/common.sh#L147

**Comment by holgerstolzenberg** [comment]
Can you give it a try after the latest build has been pushed: https://github.com/cathive/concourse-sonarqube-resource/actions/runs/6665853754
